### ISSUE TITLE
Open Source CryptFolio & Openclerk?

### ISSUE THREAD

**Issue by Francewhoa** [soundasleep/openclerk#31]
Hi there soundasleep/Jevon :)

Are you interested in keeping open source both CryptFolio & Openclerk? I mean presently and in the future.

I'm asking because I'm interested to join, use, and contribute only projects which are committed to be and remain fully open source. You mentioned that you're considering a not-fully open source model for CryptFolio. Really no interference intended. Feel really free to go on any road to your liking.

Cheers,

Francewhoa

<hr>

For those not familiar with some of the benefits of the open source business model:

# Investor

As an investor, why are open source software a better investment for you? 
• Faster, bigger, longer term profit $
• Video about why open source software better for you as investor at https://youtu.be/fch9WjHjAXI 
 

# Founder

As an organization founder, why are open source software better for you? 
• Faster growth. Because your project is more attractive to contributors.

• Monetize. Optionally, you can offer paid services based on the code. Such as sell your time, sell warranties and other assurances, sell customization and maintenance work, license the trademark, etc. The only kind of profit strategy that is incompatible with Open Source is monopoly-based sales, also known as "royalties". See this article for how to think about business strategies at:
http://blogs.fsfe.org/greve/?p=260 
And https://opensource.org/faq#commercial 
Related video at https://www.youtube.com/watch?v=c3rfp6JDzjk&feature=youtu.be&t=3m28s 

• Video about why open source software better for you as founder at https://youtu.be/fch9WjHjAXI 

• More secure. Because the software source code is available for public review and contributions. 

• Do not be fooled by the common myths about using open source software at https://youtu.be/s-xDnW8Kt8Y 
 

# User

• More secure. Because the software source code is available for public review and contributions.

• No strings attached. Read more about vendor lock-in at https://en.wikipedia.org/wiki/Vendor_lock-in

• Serves you. When the software code is owned by a not-for-profit community or organization it means their first priority is to serve you and protect your privacy. Compare to software code owned by a for-profit corporation. Where their usual first priority is to hoard money. And sell your private information to monetize it.

• Video about why are open source software better for you at https://youtu.be/ZPPikY3uLIQ 

• Do not be fool by “free software” versus “open source” software. Watch video at https://youtu.be/c3rfp6JDzjk 

• What is Open Source? Watch video at https://youtu.be/1ehpgbb3XD0

**Comment by soundasleep** [comment]
Thank you for your passionate pitch!

I absolutely 100000% want to keep the new CryptFolio open source. I am a massive fan of open source. Unfortunately there are a lot of aspects of running a SaaS platform that require cash: design, assets, translation, support, hosting, licensing fees, and more.

I've tried to attract contributors for Openclerk in the past, so that the platform can be self-sustaining, but it seems the market size is not yet mature or large enough to attract enough contributors to make the platform a success.

Consequently, for us to have the funds to continue development, I had to make the difficult decision to lock away some of our IP and assets behind a proprietary license. This is common with most other SaaS platforms.

If, at any point in the future, CryptFolio has enough assets/resources/community to open source the entire project, I will absolutely do so. I'm also considering open sourcing the core platform (without proprietary assets) if there is actually a community that would want to support it.

We also have a pricing model that allows you to gain full access to the source code, giving you many of the benefits of open source, but also ensuring we have the funds to maintain and develop the platform: https://cryptfolio.com/pricing

In the meantime, the original openclerk will remain open source, and open to contributors. We'll be releasing as many components of our platform as open source as possible. So please continue contributing to openclerk, I'll be very happy to continue merging your PRs and maintaining the platform! <3
